create table if not exists public.events (
  id text primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  payload jsonb not null
);

create table if not exists public.event_registrations (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null references public.events(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  status text not null default 'active' check (status in ('active', 'revoked')),
  cancelled_at timestamptz,
  registration_token uuid not null default gen_random_uuid(),
  primary key (registration_token)
);

alter table public.event_registrations
  add column if not exists status text not null default 'active';
alter table public.event_registrations
  add column if not exists cancelled_at timestamptz;
alter table public.event_registrations
  add column if not exists registration_token uuid default gen_random_uuid();
alter table public.event_registrations
  alter column registration_token set not null;
alter table public.event_registrations
  drop constraint if exists event_registrations_pkey;
alter table public.event_registrations
  add constraint event_registrations_pkey primary key (registration_token);

create or replace function public.activate_event_registration(
  requested_event_id text,
  event_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if exists (
    select 1
    from public.event_registrations
    where user_id = auth.uid()
      and event_id = requested_event_id
      and status = 'active'
  ) then
    raise exception 'Already registered for this event';
  end if;

  insert into public.event_registrations (user_id, event_id, payload, status, cancelled_at)
  values (auth.uid(), requested_event_id, event_payload, 'active', null);
end;
$$;

create or replace function public.revoke_event_registration(requested_event_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.event_registrations
  set status = 'revoked', cancelled_at = now()
  where user_id = auth.uid()
    and event_id = requested_event_id
    and status = 'active';
end;
$$;

create or replace function public.validate_event_registration(
  requested_token uuid,
  requested_event_id text
)
returns table (
  event_id text,
  user_id uuid,
  status text,
  registered_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not (
    (auth.jwt() -> 'app_metadata' -> 'roles') ? 'watcher'
    or (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  ) then
    raise exception 'Watcher access required';
  end if;

  return query
    select registration.event_id,
           registration.user_id,
           registration.status,
           registration.created_at
    from public.event_registrations as registration
    where registration.registration_token = requested_token
      and registration.event_id = requested_event_id
      and registration.status = 'active';
end;
$$;

revoke all on function public.activate_event_registration(text, jsonb) from public;
grant execute on function public.activate_event_registration(text, jsonb) to authenticated;
revoke all on function public.revoke_event_registration(text) from public;
grant execute on function public.revoke_event_registration(text) to authenticated;
revoke all on function public.validate_event_registration(uuid, text) from public;
grant execute on function public.validate_event_registration(uuid, text) to authenticated;

create table if not exists public.role_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_role text not null check (requested_role in ('user', 'admin', 'watcher')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (user_id, requested_role, status)
);

create table if not exists public.event_check_ins (
  registration_token uuid primary key references public.event_registrations(registration_token) on delete cascade,
  event_id text not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  checked_in_by uuid not null references auth.users(id) on delete restrict,
  checked_in_at timestamptz not null default now()
);

alter table public.event_check_ins enable row level security;

drop function if exists public.check_in_event_registration(uuid, text);
create or replace function public.check_in_event_registration(
  requested_token uuid,
  requested_event_id text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  registration public.event_registrations%rowtype;
  inserted_token uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not (
    (auth.jwt() -> 'app_metadata' -> 'roles') ? 'watcher'
    or (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  ) then
    raise exception 'Watcher access required';
  end if;

  select * into registration
  from public.event_registrations
  where registration_token = requested_token
    and event_id = requested_event_id
    and status = 'active';

  if not found then
    return 'invalid';
  end if;

  insert into public.event_check_ins (
    registration_token, event_id, user_id, checked_in_by
  ) values (
    registration.registration_token,
    registration.event_id,
    registration.user_id,
    auth.uid()
  ) on conflict (registration_token) do nothing
  returning registration_token into inserted_token;

  if inserted_token is null then
    return 'already_checked_in';
  end if;
  return 'checked_in';
end;
$$;
revoke all on function public.check_in_event_registration(uuid, text) from public;
grant execute on function public.check_in_event_registration(uuid, text) to authenticated;

create or replace function public.load_event_attendance_count(requested_event_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin' then
    raise exception 'Admin access required';
  end if;

  if not exists (
    select 1
    from public.events
    where id = requested_event_id
      and creator_id = auth.uid()
  ) then
    raise exception 'Event access denied';
  end if;

  return (
    select count(*)
    from public.event_check_ins
    where event_id = requested_event_id
  );
end;
$$;
revoke all on function public.load_event_attendance_count(text) from public;
grant execute on function public.load_event_attendance_count(text) to authenticated;

create or replace function public.create_role_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text := new.raw_user_meta_data ->> 'requested_role';
begin
  if requested_role in ('user', 'admin', 'watcher') then
    insert into public.role_requests (user_id, requested_role)
    values (new.id, requested_role)
    on conflict (user_id, requested_role, status) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_role_request on auth.users;
create trigger on_auth_user_created_role_request
  after insert on auth.users
  for each row execute function public.create_role_request();

alter table public.events enable row level security;
alter table public.event_registrations enable row level security;
alter table public.role_requests enable row level security;

create policy "Authenticated users can view events"
  on public.events for select
  to authenticated
  using (true);

create policy "Admins can create their events"
  on public.events for insert
  to authenticated
  with check (
    auth.uid() = creator_id
    and (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  );

create policy "Creators can update their events"
  on public.events for update
  to authenticated
  using (
    auth.uid() = creator_id
    or (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  )
  with check (
    auth.uid() = creator_id
    or (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  );

create policy "Creators can delete their events"
  on public.events for delete
  to authenticated
  using (
    auth.uid() = creator_id
    or (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
  );

create policy "Users can view their registrations"
  on public.event_registrations for select
  to authenticated
  using (auth.uid() = user_id and status = 'active');

create unique index if not exists event_registrations_token_idx
  on public.event_registrations (registration_token);
create unique index if not exists event_registrations_active_user_event_idx
  on public.event_registrations (user_id, event_id)
  where status = 'active';

create policy "Users can create their registrations"
  on public.event_registrations for insert
  to authenticated
  with check (false);

create policy "Users can delete their registrations"
  on public.event_registrations for delete
  to authenticated
  using (auth.uid() = user_id);

-- Data API grants are separate from RLS. Keep row access restricted by the
-- policies above while explicitly exposing the table to signed-in clients.
grant usage on schema public to authenticated;
grant select, delete on table public.event_registrations to authenticated;

create policy "Users can view their role requests"
  on public.role_requests for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Admins can view role requests"
  on public.role_requests for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin');

create policy "Admins can review role requests"
  on public.role_requests for update
  to authenticated
  using ((auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin')
  with check ((auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin');

create index if not exists events_creator_id_idx
  on public.events (creator_id);

create index if not exists event_registrations_event_id_idx
  on public.event_registrations (event_id);

notify pgrst, 'reload schema';