-- Server-side foundations for drafts, invitations, visibility, and login activity.
alter table public.events
  add column if not exists lifecycle_status text not null default 'published'
    check (lifecycle_status in ('draft', 'published', 'archived'));

alter table public.events
  add column if not exists registration_visibility text not null default 'public'
    check (registration_visibility in ('public', 'private'));

create index if not exists events_creator_status_idx
  on public.events (creator_id, lifecycle_status);

create table if not exists public.event_invitations (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  inviter_id uuid not null references auth.users(id) on delete cascade,
  invitee_id uuid references auth.users(id) on delete cascade,
  invitee_email text,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'revoked')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (invitee_id is not null or invitee_email is not null),
  unique (event_id, invitee_id),
  unique (event_id, invitee_email)
);

alter table public.event_invitations enable row level security;

create policy event_invitations_select on public.event_invitations
  for select using (inviter_id = auth.uid() or invitee_id = auth.uid());
create policy event_invitations_insert on public.event_invitations
  for insert with check (inviter_id = auth.uid());
create policy event_invitations_update on public.event_invitations
  for update using (inviter_id = auth.uid() or invitee_id = auth.uid());

create table if not exists public.profile_visibility_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile_visibility text not null default 'private'
    check (profile_visibility in ('private', 'registered_users', 'public')),
  registration_visibility text not null default 'private'
    check (registration_visibility in ('private', 'organizers', 'public')),
  updated_at timestamptz not null default now()
);

alter table public.profile_visibility_settings enable row level security;
create policy profile_visibility_self on public.profile_visibility_settings
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.login_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signed_in_at timestamptz not null default now(),
  device_label text,
  platform text,
  ip_address inet
);

alter table public.login_activity enable row level security;
create policy login_activity_self on public.login_activity
  for select using (user_id = auth.uid());

create or replace function public.record_login_activity(
  requested_device_label text default null,
  requested_platform text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  insert into public.login_activity (user_id, device_label, platform)
  values (auth.uid(), requested_device_label, requested_platform);
end;
$$;

revoke all on function public.record_login_activity(text, text) from public;
grant execute on function public.record_login_activity(text, text) to authenticated;

create or replace function public.list_invitation_recipients()
returns table (user_id uuid, display_name text, email text)
language sql
security definer
set search_path = public
as $$
  select users.id,
         coalesce(users.raw_user_meta_data ->> 'display_name', '') as display_name,
         users.email
  from auth.users as users
  where (auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin'
    and users.id <> auth.uid()
  order by display_name, email;
$$;

create or replace function public.send_event_invitations(
  requested_event_id text,
  requested_user_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if not ((auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin') then
    raise exception 'Admin access required';
  end if;
  if not exists (select 1 from public.events where id = requested_event_id) then
    raise exception 'Event not found';
  end if;

  insert into public.event_invitations (event_id, inviter_id, invitee_id)
  select requested_event_id, auth.uid(), recipient
  from unnest(requested_user_ids) as recipient
  where recipient <> auth.uid()
  on conflict (event_id, invitee_id) do nothing;
  get diagnostics inserted_count = row_count;

  insert into public.notifications (
    user_id, event_id, notification_type, title, message, event_date
  )
  select invitation.invitee_id,
         event.id,
         'invitation',
         'You are invited to an event',
         'You have been invited to ' || coalesce(event.payload ->> 'title', 'an event') || '.',
         case
           when event.payload ->> 'date' ~ '^\d{4}-\d{2}-\d{2}'
             then (event.payload ->> 'date')::date
           else to_date(event.payload ->> 'date', 'DD/MM/YYYY')
         end
  from public.event_invitations as invitation
  join public.events as event on event.id = invitation.event_id
  where invitation.event_id = requested_event_id
    and invitation.inviter_id = auth.uid()
    and invitation.invitee_id = any(requested_user_ids)
    and invitation.status = 'pending'
  on conflict (user_id, event_id, notification_type) do nothing;
  return inserted_count;
end;
$$;

create or replace function public.respond_to_event_invitation(
  requested_event_id text,
  requested_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  invitation public.event_invitations%rowtype;
  event_payload jsonb;
begin
  if requested_status not in ('accepted', 'declined') then
    raise exception 'Invalid invitation response';
  end if;
  select * into invitation
  from public.event_invitations
  where event_id = requested_event_id
    and invitee_id = auth.uid()
    and status = 'pending'
  order by created_at desc
  limit 1;
  if not found then raise exception 'Invitation not found'; end if;

  update public.event_invitations
  set status = requested_status, responded_at = now()
  where id = invitation.id;

  if requested_status = 'accepted' then
    select payload into event_payload from public.events where id = requested_event_id;
    insert into public.event_registrations (user_id, event_id, payload, status)
    values (auth.uid(), requested_event_id, event_payload, 'active')
    on conflict do nothing;
  end if;
end;
$$;

revoke all on function public.list_invitation_recipients() from public;
revoke all on function public.send_event_invitations(text, uuid[]) from public;
revoke all on function public.respond_to_event_invitation(text, text) from public;
grant execute on function public.list_invitation_recipients() to authenticated;
grant execute on function public.send_event_invitations(text, uuid[]) to authenticated;
grant execute on function public.respond_to_event_invitation(text, text) to authenticated;

drop function if exists public.load_user_notifications();
create or replace function public.load_user_notifications()
returns table (
  id bigint,
  "eventId" text,
  "notificationType" text,
  title text,
  message text,
  "eventDate" date,
  "createdAt" timestamptz,
  "isRead" boolean,
  "arrivalStatus" text
)
language sql
security definer
set search_path = public
as $$
  select notification.id,
         notification.event_id,
         notification.notification_type,
         notification.title,
         notification.message,
         notification.event_date,
         notification.created_at,
         notification.is_read,
         coalesce(arrival.status, 'pending')
  from public.notifications as notification
  left join public.event_arrivals as arrival
    on arrival.event_id = notification.event_id
   and arrival.user_id = notification.user_id
  where notification.user_id = auth.uid()
    and not exists (
      select 1
      from public.event_invitations as invitation
      where invitation.event_id = notification.event_id
        and invitation.invitee_id = auth.uid()
        and invitation.status in ('accepted', 'declined')
        and notification.notification_type = 'invitation'
    )
  order by notification.created_at desc
  limit 50;
$$;

revoke all on function public.load_user_notifications() from public;
grant execute on function public.load_user_notifications() to authenticated;