-- Server-side foundations for drafts, invitations, visibility, and login activity.
alter table public.events
  add column if not exists lifecycle_status text not null default 'published'
    check (lifecycle_status in ('draft', 'published', 'archived'));

alter table public.events
  add column if not exists registration_visibility text not null default 'public'
    check (registration_visibility in ('public', 'private'));

create index if not exists events_creator_status_idx
  on public.events (creator_id, lifecycle_status);

create table if not exists public.event_invitations (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  inviter_id uuid not null references auth.users(id) on delete cascade,
  invitee_id uuid references auth.users(id) on delete cascade,
  invitee_email text,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'revoked')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (invitee_id is not null or invitee_email is not null),
  unique (event_id, invitee_id),
  unique (event_id, invitee_email)
);

alter table public.event_invitations enable row level security;

create policy event_invitations_select on public.event_invitations
  for select using (inviter_id = auth.uid() or invitee_id = auth.uid());
create policy event_invitations_insert on public.event_invitations
  for insert with check (inviter_id = auth.uid());
create policy event_invitations_update on public.event_invitations
  for update using (inviter_id = auth.uid() or invitee_id = auth.uid());

create table if not exists public.profile_visibility_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile_visibility text not null default 'private'
    check (profile_visibility in ('private', 'registered_users', 'public')),
  registration_visibility text not null default 'private'
    check (registration_visibility in ('private', 'organizers', 'public')),
  updated_at timestamptz not null default now()
);

alter table public.profile_visibility_settings enable row level security;
create policy profile_visibility_self on public.profile_visibility_settings
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.login_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signed_in_at timestamptz not null default now(),
  device_label text,
  platform text,
  ip_address inet
);

alter table public.login_activity enable row level security;
create policy login_activity_self on public.login_activity
  for select using (user_id = auth.uid());

create or replace function public.record_login_activity(
  requested_device_label text default null,
  requested_platform text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  insert into public.login_activity (user_id, device_label, platform)
  values (auth.uid(), requested_device_label, requested_platform);
end;
$$;

revoke all on function public.record_login_activity(text, text) from public;
grant execute on function public.record_login_activity(text, text) to authenticated;