create table if not exists public.event_arrivals (
  registration_token uuid primary key
    references public.event_registrations(registration_token) on delete cascade,
  event_id text not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'attending', 'not_attending')),
  confirmed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (event_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null references public.events(id) on delete cascade,
  notification_type text not null,
  title text not null,
  message text not null,
  event_date date not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, event_id, notification_type)
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);
create index if not exists event_arrivals_event_status_idx
  on public.event_arrivals (event_id, status);

alter table public.event_arrivals enable row level security;
alter table public.notifications enable row level security;

create or replace function public.load_user_notifications()
returns table (
  id bigint,
  "eventId" text,
  title text,
  message text,
  "eventDate" date,
  "createdAt" timestamptz,
  "isRead" boolean,
  "arrivalStatus" text
)
language sql
security definer
set search_path = public
as $$
  select notification.id,
         notification.event_id,
         notification.title,
         notification.message,
         notification.event_date,
         notification.created_at,
         notification.is_read,
         coalesce(arrival.status, 'pending')
  from public.notifications as notification
  left join public.event_arrivals as arrival
    on arrival.event_id = notification.event_id
   and arrival.user_id = notification.user_id
  where notification.user_id = auth.uid()
  order by notification.created_at desc
  limit 50;
$$;

create or replace function public.count_user_unread_notifications()
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)
  from public.notifications
  where user_id = auth.uid()
    and is_read = false;
$$;

create or replace function public.mark_notification_read(
  requested_notification_id bigint
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.notifications
  set is_read = true
  where id = requested_notification_id
    and user_id = auth.uid();
$$;

create or replace function public.update_event_arrival_status(
  requested_event_id text,
  requested_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  registration_token uuid;
begin
  if requested_status not in ('attending', 'not_attending') then
    raise exception 'Invalid arrival status';
  end if;

  select registration.registration_token
    into registration_token
  from public.event_registrations as registration
  where registration.event_id = requested_event_id
    and registration.user_id = auth.uid()
    and registration.status = 'active'
  limit 1;

  if registration_token is null then
    raise exception 'Active registration required';
  end if;

  insert into public.event_arrivals (
    registration_token, event_id, user_id, status, confirmed_at
  ) values (
    registration_token, requested_event_id, auth.uid(), requested_status, now()
  )
  on conflict (registration_token) do update
    set status = excluded.status,
        confirmed_at = excluded.confirmed_at,
        updated_at = now();
end;
$$;

-- Called once per day by Supabase Cron. The unique key makes this safe to rerun.
create or replace function public.create_event_reminders()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  insert into public.notifications (
    user_id, event_id, notification_type, title, message, event_date
  )
  select registration.user_id,
         event.id,
         'arrival_confirmation_2_days',
         'Confirm your event arrival',
         'Please confirm whether you will attend ' ||
           coalesce(event.payload ->> 'title', 'this event') || '.',
         event_date.value
  from public.event_registrations as registration
  join public.events as event on event.id = registration.event_id
  cross join lateral (
    select case
      when event.payload ->> 'date' ~ '^\d{4}-\d{2}-\d{2}'
        then (event.payload ->> 'date')::date
      else to_date(event.payload ->> 'date', 'DD/MM/YYYY')
    end as value
  ) as event_date
  where registration.status = 'active'
    and event_date.value = current_date + 2
  on conflict (user_id, event_id, notification_type) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.load_user_notifications() from public;
revoke all on function public.count_user_unread_notifications() from public;
revoke all on function public.mark_notification_read(bigint) from public;
revoke all on function public.update_event_arrival_status(text, text) from public;
revoke all on function public.create_event_reminders() from public;
grant execute on function public.load_user_notifications() to authenticated;
grant execute on function public.count_user_unread_notifications() to authenticated;
grant execute on function public.mark_notification_read(bigint) to authenticated;
grant execute on function public.update_event_arrival_status(text, text) to authenticated;

-- One daily job is enough: the unique notification key makes retries harmless.
create extension if not exists pg_cron with schema extensions;
select cron.unschedule(jobid)
from cron.job
where jobname = 'event-arrival-reminders';
select cron.schedule(
  'event-arrival-reminders',
  '0 9 * * *',
  $$select public.create_event_reminders();$$
);